# Generated by Django 5.1.6 on 2025-02-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/'),
        ),
    ]
