# Generated by Django 5.1.6 on 2025-02-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_barber_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
