name: Django CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r BarberShopTest/requirements.txt
      - name: Run Tests
        run: python  BarberShopTest/manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: TEST-*.xml
      - name: Run PEP8
        continue-on-error: true
        run: pycodestyle --exclude ".venv,**/migrations/" --max-line-length 120 --format '::warning file=%(path)s,line=%(row)d,col=%(col)d::%(code)s %(text)s'  .
      - name: Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          exclude: './.venv'

  docker-test:
    needs: 'quality-check'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: build local container
        uses: docker/build-push-action@v4
        with:
          tags: ropi0955/barber-test:latest
          push: false
          load: true
      - name: Scan image
        uses: anchore/scan-action@v6
        id: scan
        with:
          image: "ropi0955/barber-test:latest"
          fail-build: true
          severity-cutoff: critical
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}