name: Django CD

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-conventional-commits@v1.3.0
      - name: Parse version
        run: |
          version=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=\()\d+\.\d+\.\d+(?=\))')
          echo $version
          
          echo "VERSION=$version" >> $GITHUB_ENV


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ropi0955/barber-test:${{ env.VERSION }},ropi0955/barber-test:latest

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: 'container-app-weu-gaborka812'
          resourceGroup: 'rgrp-weu-gaborka812-webapp'
          imageToDeploy: docker.io/ropi0955/barber-test:${{ env.VERSION }}